# Generated by Django 3.1.6 on 2021-02-16 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_todos_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoapp',
            name='date',
        ),
    ]
