# Generated by Django 3.1.6 on 2021-02-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_todoapp_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='todos',
            name='todo_completed',
            field=models.BooleanField(null=True),
        ),
    ]
